CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
	idEmpresa SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(20),
	endereco VARCHAR(150)
);
GO

CREATE TABLE MARCA(
	idMarca TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeMarca VARCHAR(20),
);
GO

CREATE TABLE MODELO(
	idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeModelo VARCHAR(15) NOT NULL,
	idMarca TINYINT FOREIGN KEY REFERENCES MARCA(idMarca)
);
GO

CREATE TABLE VEICULO(
	idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
	idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
	idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	placa VARCHAR(8) NOT NULL
);
GO

CREATE TABLE CLIENTE(
	idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
	nome VARCHAR(15) NOT NULL,
	RG VARCHAR(12) NOT NULL
);
GO

CREATE TABLE ALUGUEL(
	idAluguel INT PRIMARY KEY IDENTITY(1,1),
	idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	preco SMALLMONEY NOT NULL,
	Adata DATE 
);
GO